print("Start a program")
s1 = input("Enter some text: ")
print("Entered text " , s1)
print(type(s1))
s2 = int(input("Enter some number "))
print("Entered number ", s2)
print(type(s2))
s3 = float(input("Enter some fraction number "))
print("Enter fractional number is ", s3)
print(type(s3))
print("End of program")

#----------------------------------------------------------------------#

n1 = int(input("Enter number 1 "))
n2 = int(input("Enter number 2 "))
print("Addition - ", n1 + n2)
print("Subtraction - ", n1 - n2)
print("Multiplication - ", n1 * n2)
print("Division - ", n1 / n2)
print("Exponentitial - ", n1 ** n2)
print("Remainder - ", n1 % n2)
print("Right shift" , n1 >> n2)
print("Left shift", n1 << n2)